import { renderReleaseDesk, renderTodayOverview, renderMarketSpotlight } from './workspaces.js';
import { esc } from './util.js';
import { sourceLink } from './ui.js';
import { snapshotLabel, adoptionMetric as m, formatShare, adoptionSummary } from './metric-meta.js';
import { marketShare } from './curated.js';
import { cleanReleases } from '../scripts/lib/releases.mjs';
export function renderAdoption(){const root=document.getElementById('sec-market');root.innerHTML=`<div class="panel"><p class="eyebrow">Adoption, with a precise definition</p><h2>${m.label}</h2><p>${m.definition}</p><p class="meta">${m.period} · Curated ${m.updatedAt} · ${sourceLink(m.sourceUrl,m.sourceName)}</p><p class="benchmark-info">${m.limitations}</p>${marketShare.map(r=>`<div class="adoption-row"><span>${esc(r.name)}</span><div class="adoption-track"><div class="adoption-fill" style="width:${r.pct}%"></div></div><strong>${esc(formatShare(r.pct))}</strong></div>`).join('')}<p class="meta">Bar scale: 0–100% of measured chatbot referrals.</p><p>${esc(adoptionSummary())}</p></div>`;}
export function renderLive(data){
 const releases=(data.releases||[]).map(r=>({...r,items:cleanReleases(r.items||[])}));
 renderReleaseDesk(releases,data.updatedAt);renderTodayOverview(data,releases);
 const newest=releases.flatMap(r=>r.items.map(i=>({...i,lab:r.lab}))).sort((a,b)=>(Date.parse(b.d)||0)-(Date.parse(a.d)||0)).slice(0,3);
 document.getElementById('recent-releases').innerHTML=newest.length?`<ol class="data-list panel">${newest.map(i=>`<li><div>${sourceLink(i.url,i.h)}<small>${esc(i.lab)} · ${esc(i.d)}</small></div></li>`).join('')}</ol>`:'<p class="empty-state">No qualifying releases in this snapshot.</p>';
 const compute=data.compute||[];
 document.getElementById('compute-cards').innerHTML=compute.map((c,i)=>`<article class="compute-card"><div class="compute-card-top"><span class="rank-guide-label">GPU RENTAL / ${String(i+1).padStart(2,'0')}</span><span class="compute-trend">${esc(c.trend)}</span></div><h3>${esc(c.chip)}</h3><p>${esc(c.segment)}</p><div class="compute-rate">${esc(c.rate)}</div><small>USD per GPU hour · collected marketplace offers</small><details><summary>Offer context</summary><p>${esc(c.note)}</p><p>Availability, memory, region, and extra fees vary. Confirm the offer with the provider.</p></details></article>`).join('');

 document.getElementById('compute-rows').innerHTML=compute.length?compute.map(c=>`<tr><th scope="row">${esc(c.chip)}</th><td>${esc(c.segment)}</td><td>${esc(c.rate)}</td><td>${esc(c.trend)}</td><td>${esc(c.note)}</td></tr>`).join(''):'<tr><td colspan="5">GPU listings are unavailable. <button class="button" data-retry="latest">Retry listings</button></td></tr>';
 document.getElementById('compute-asof').textContent=snapshotLabel(data.updatedAt)+' · automatic marketplace collection';
}
export function renderStocks(net,fallback){const nodes=net?.nodes?.length?net.nodes:(fallback?.stocks||[]);renderMarketSpotlight(nodes,net?.updatedAt||fallback?.updatedAt);document.getElementById('stock-table-asof').textContent=snapshotLabel(net?.updatedAt||fallback?.updatedAt)+' · collection time';document.getElementById('stock-table').innerHTML=nodes.length?`<div class="table-wrap"><table class="stock-table"><caption>AI stock snapshots · USD · Yahoo Finance</caption><thead><tr><th scope="col">Company</th><th scope="col">Price</th><th scope="col">Daily change</th><th scope="col">Last bar (MM-DD)</th><th scope="col">Source</th></tr></thead><tbody>${nodes.map(n=>`<tr><th scope="row">${esc(n.t)}<br><span class="meta">${esc(n.n||n.name||'')}</span></th><td>${Number.isFinite(n.price)?'$'+n.price.toFixed(2):'Not available'}</td><td>${Number.isFinite(n.changePct)?(n.changePct>0?'+':'')+n.changePct.toFixed(2)+'%'+(n.changeReview?' · Review unusual move':''):'Not available'}</td><td>${esc(n.chart?.at(-1)?.d||'Not available')}</td><td>${sourceLink(n.url||'https://finance.yahoo.com/quote/'+encodeURIComponent(n.t),'Quote')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">Stock snapshots are unavailable. <button class="button" data-retry="stocks">Retry stocks</button></p>';}
export { renderVideos } from './video-gallery.js';
