import { createOceanMap } from './oceanmap.js';
import { esc } from './util.js';
import { openDialog,sourceLink } from './ui.js';
let nodes=[],layers=[],connections=[],data={},ranges=null,range='24H',map=null,query='';
function activity(){return ranges?.ranges?.[range]||{entityActivity:range==='24H'?data.entityActivity||{}:{},entityDelta:{},previousWindowComplete:false};}
function detail(id){const n=nodes.find(n=>n.id===id);if(!n)return;const r=activity(),count=r.entityActivity?.[id];openDialog(n.name,`<p class="meta">${esc(n.org||'')} · ${esc(layers.find(l=>l.id===n.layer)?.label||layers.find(l=>l.id===n.layer)?.name||'Layer '+n.layer)}</p><p>Version in this snapshot: ${esc(n.version||n.name)}</p><p>${esc(n.why||'')}</p><p>${count??'No available'} signals in ${esc(range)}. ${r.previousWindowComplete?'Change from the prior window: '+esc(r.entityDelta?.[id]??'unavailable'):'Not enough history for a comparison.'}</p><h3>Stories in the loaded feed</h3><ul>${(data.signals||[]).filter(s=>s.entityIds?.includes(id)).slice(0,8).map(s=>`<li>${sourceLink(s.url,s.title)}</li>`).join('')||'<li>No individual stories in the loaded feed. Range counts may cover a longer history.</li>'}</ul><h3>Connections</h3><ul>${connections.filter(c=>c.from===id||c.to===id).map(c=>{const other=nodes.find(n=>n.id===(c.from===id?c.to:c.from));const phrase=c.type==='depends'?(c.from===id?'Depends on':'Provides infrastructure for'):c.type==='partner'?'Partners with':'Competes with';return `<li>${phrase} ${esc(other?.name||'Unknown entity')}</li>`;}).join('')||'<li>No curated relationships in this dataset.</li>'}</ul><p>${(n.links||[]).map(l=>sourceLink(l.url,l.label)).join(' · ')}</p>`);}
function draw(){const r=activity(),filtered=nodes.filter(n=>[n.name,n.org,n.why].join(' ').toLowerCase().includes(query.toLowerCase()));
 const html=filtered.length?filtered.map(n=>`<article class="entity-card"><div><h3>${esc(n.name)} <span class="meta">${esc(n.org||'')}</span></h3><p>${esc(layers.find(l=>l.id===n.layer)?.label||layers.find(l=>l.id===n.layer)?.name||'Layer '+n.layer)} · ${r.entityActivity?.[n.id]??'Unavailable'} signals / ${range}</p></div><button class="button quiet" data-entity="${esc(n.id)}">Details <span class="sr-only">for ${esc(n.name)}</span></button></article>`).join(''):'<p class="empty-state">No entities match. Clear the search to see every entity.</p>';
 document.getElementById('entity-list').innerHTML=html;document.getElementById('entity-results').innerHTML=query?html:'';
 document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>detail(b.dataset.entity));
 document.getElementById('history-note').textContent=(ranges?.historyDepthDays?Math.floor(ranges.historyDepthDays)+' days of recorded history. ':'')+(r.previousWindowComplete?'Comparing '+range+' with the preceding window.':ranges?.ranges?.[range]?'Activity covers the available portion of this window; not enough history for a comparison.':range==='24H'?'Using the latest 24-hour snapshot; prior-window history is unavailable.':'Activity and comparison are unavailable for this window. Try 24H.');
 map?.update({activity:r.entityActivity||{},delta:r.entityDelta||{},rangeLabel:range,historyAvailable:!!r.previousWindowComplete,signals:data.signals||[]});
}
function ensureMap(){if(map||!nodes.length)return;const view=new URL(location.href).searchParams;if(view.get('view')==='ecosystem'&&view.get('mode')!=='list'&&view.get('mode')!=='adoption'){map=createOceanMap(document.getElementById('ocean-map'),{nodes,layers,connections});draw();}}
export function initEcosystem(){document.getElementById('entity-search').oninput=e=>{query=e.target.value;draw();};document.querySelectorAll('.range-btn').forEach(b=>b.onclick=()=>{range=b.dataset.range;document.querySelectorAll('.range-btn').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();});document.getElementById('reset-entity').onclick=()=>{query='';document.getElementById('entity-search').value='';map?.closeDrawer();draw();};addEventListener('app:view',e=>{const adoption=e.detail.view==='ecosystem'&&e.detail.mode==='adoption';document.getElementById('ecosystem-controls').hidden=adoption;document.getElementById('history-note').hidden=adoption;ensureMap();});}
export function updateEcosystem(entities,latest,history){if(entities){nodes=entities.nodes||[];layers=entities.layers||[];connections=entities.connections||[];}data=latest||{};ranges=history;if(!nodes.length){const msg='<p class="empty-state">Ecosystem data is unavailable. <button class="button" data-retry="entities">Retry ecosystem</button></p>';document.getElementById('entity-list').innerHTML=msg;document.getElementById('ocean-map').innerHTML=msg;return;}ensureMap();draw();}
