import * as C from './curated.js';
import { esc } from './util.js';
import { openDialog, sourceLink } from './ui.js';
const explanations={overall:'Artificial Analysis Intelligence Index combines several evaluations. A higher score indicates stronger results on those tests; it does not predict every task.',reasoning:"Humanity's Last Exam measures difficult reasoning questions. These percentages come from the same Artificial Analysis evaluation.",agentic:'Terminal-Bench 4.0 measures completion of tasks in a terminal environment. Higher is better within this evaluation.',cost:'A relative cost-efficiency index for this roster, derived from estimated cost per task. 100 is the lowest cost here, not a provider price or a quality score.'};
const links={text:'https://artificialanalysis.ai/leaderboards/models',image:'https://artificialanalysis.ai/image/leaderboard/text-to-image',video:'https://artificialanalysis.ai/video/leaderboard/text-to-video',local:'https://huggingface.co/models'};
let selected=[],category='text',benchmark='overall',rows=C.leaderboardOverall;
const status=()=>document.getElementById('compare-status');
function tray(){const root=document.getElementById('compare-tray');root.hidden=!selected.length;root.innerHTML=`<strong>${selected.length} of 3 selected</strong>${selected.map(name=>`<button class="button quiet" data-remove="${esc(name)}" aria-label="Remove ${esc(name)}">${esc(name)} ×</button>`).join('')}<button class="button" id="compare-open" ${selected.length<2?'disabled':''}>Compare${selected.length<2?' · select one more':''}</button><button class="button" id="compare-clear">Clear</button>`;root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(n=>n!==b.dataset.remove);syncChecks();tray();});root.querySelector('#compare-clear')?.addEventListener('click',()=>{selected=[];syncChecks();tray();});root.querySelector('#compare-open')?.addEventListener('click',()=>{const chosen=rows.filter(r=>selected.includes(r.model));openDialog('Compare models',`<p>Same category and evaluation · curated ${esc(C.CURATED_ASOF)}. Differences are specific to this test and configuration.</p><div class="comparison" style="--count:${chosen.length}">${[['Provider',r=>r.org],['Measured result',r=>r.score!=null?r.score+(r.scoreUnit||''):'Not available'],['Context & limitations',r=>r.note],['Source',()=>sourceLink(links[category],'Evaluation source')]].map(([name,fn])=>`<section class="compare-attribute"><h3>${name}</h3><div class="compare-values">${chosen.map(r=>`<div><strong>${esc(r.model)}</strong><p>${name==='Source'?fn(r):esc(fn(r))}</p></div>`).join('')}</div></section>`).join('')}</div>`);});}
function syncChecks(){document.querySelectorAll('[data-compare]').forEach(b=>{b.checked=selected.includes(b.dataset.compare);});}
function listMarkup(data,compare=true){const max=Math.max(...data.map(r=>r.score||0));return data.map((r,i)=>`<article class="model-row"><span class="preview-rank">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(r.model)}</h3><p class="meta">${esc(r.org)}</p>${r.score!=null?`<div class="model-meter" aria-hidden="true"><span style="--score:${max?r.score/max*100:0}%"></span></div>`:''}<div class="model-actions"><button class="button quiet" data-details="${esc(r.model)}">Details <span class="sr-only">for ${esc(r.model)}</span></button>${compare?`<label><input type="checkbox" data-compare="${esc(r.model)}" ${selected.includes(r.model)?'checked':''}>Compare <span class="sr-only">${esc(r.model)}</span></label>`:''}</div></div><div class="score">${esc(r.score!=null?r.score:r.stat)}<small>${esc(r.scoreUnit||'Hardware-fit estimate')}</small></div></article>`).join('');}
function wireList(root,data,kind){root.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>{const r=data.find(r=>r.model===b.dataset.details);openDialog(r.model,`<p class="meta">${esc(r.org)} · curated ${esc(C.CURATED_ASOF)}</p><p>${esc(r.note)}</p><dl><dt>${r.score!=null?'Measured result':'Hardware guidance'}</dt><dd>${esc(r.score!=null?r.score+(r.scoreUnit||''):r.stat)}</dd></dl><p>${esc(kind==='local'?C.LOCAL_AI_SPECS_METHODOLOGY:kind==='text'?explanations[benchmark]:'Elo is a relative preference rating for this specific arena. Small differences and overlapping confidence intervals may not imply a meaningful advantage.')}</p>${sourceLink(links[kind],kind==='local'?'Browse model cards':'Read the evaluation source')}`);});root.querySelectorAll('[data-compare]').forEach(b=>b.onchange=()=>{const name=b.dataset.compare;if(b.checked){if(selected.length===3){b.checked=false;status().textContent='Compare up to 3 models. Remove one to add another.';return;}selected.push(name);}else selected=selected.filter(n=>n!==name);status().textContent=`${selected.length} models selected`;tray();});}
const evaluationLabels={overall:'Overall ability',reasoning:'Reasoning',agentic:'Coding tasks',cost:'Cost efficiency'};
const shortMeaning={overall:'A combined score across several capability tests.',reasoning:'Share of difficult reasoning questions answered correctly.',agentic:'Share of terminal-based coding tasks completed.',cost:'Relative cost efficiency. 100 is the lowest estimated cost in this roster.'};
function rankingTable(data){
 const max=Math.max(...data.map(r=>r.score||0));
 return `<div class="ranking-scroll"><table class="ranking-table"><caption class="sr-only">Model rankings for the selected evaluation. Higher scores are better. Select two or three models to compare.</caption><thead><tr><th scope="col">#</th><th scope="col">Model <span class="column-note">/ provider</span></th><th scope="col">Score <span class="column-note">↑ higher is better</span></th><th scope="col">Compare</th></tr></thead><tbody>${data.map((r,i)=>`<tr style="--row:${i}" class="${i===0?'rank-leader':''}"><td class="rank-number">${String(i+1).padStart(2,'0')}</td><th scope="row"><button class="rank-model" data-details="${esc(r.model)}" aria-label="Details for ${esc(r.model)}"><span class="provider-avatar" aria-hidden="true">${esc(r.org.slice(0,2).toUpperCase())}</span><span><strong>${esc(r.model)}</strong><small>${esc(r.org)}</small></span><span class="rank-open" aria-hidden="true">↗</span></button></th><td><div class="rank-score"><span class="rank-track" aria-hidden="true"><span style="--score:${max?r.score/max*100:0}%"></span></span><strong>${esc(r.score??'—')}</strong></div></td><td><label class="rank-select"><input type="checkbox" data-compare="${esc(r.model)}" ${selected.includes(r.model)?'checked':''}><span class="sr-only">Compare ${esc(r.model)}</span></label></td></tr>`).join('')}</tbody></table></div>`;
}
function renderCategory(kind){
 const root=document.getElementById('model-'+kind),data=kind==='text'?C.LEADERBOARD_VIEWS.find(v=>v.id===benchmark).data:kind==='image'?C.imageAI:C.videoAI;
 if(category===kind)rows=data;
 const title=kind==='text'?'Text models':kind==='image'?'Image models':'Video models';
 const unit=kind==='text'?data[0]?.scoreUnit?.trim():'Elo';
 const meaning=kind==='text'?shortMeaning[benchmark]:'A relative rating from human preferences in this category. It is not a percentage.';
 root.innerHTML=`<div class="rank-dashboard"><div class="rank-toolbar"><div><h2>${title}</h2><span class="rank-count">${data.length} models · ${esc(unit)}</span></div>${kind==='text'?`<label class="rank-sort">Rank by<select id="benchmark">${C.LEADERBOARD_VIEWS.map(v=>`<option value="${v.id}" ${v.id===benchmark?'selected':''}>${evaluationLabels[v.id]}</option>`).join('')}</select></label>`:'<span class="rank-count">Ranked by human preference</span>'}<button class="button quiet rank-help" data-score-help>ⓘ About the score</button></div><div class="rank-layout"><div>${rankingTable(data)}<div class="rank-table-foot"><span>Click a model for details · select 2–3 to compare</span><span>Bars relative to the leader</span></div></div><aside class="rank-guide"><p class="rank-guide-label">HOW TO READ THIS</p><h3>${kind==='text'?evaluationLabels[benchmark]:'Human preference'}</h3><p>${meaning}</p><div class="rank-top"><span>Leading this evaluation</span><strong>${esc(data[0]?.model||'Unavailable')}</strong><b>${esc(data[0]?.score??'—')} <small>${esc(unit)}</small></b></div><p class="rank-caution">A higher rank on this test does not mean a model is best for every task.</p><div class="rank-provenance">${sourceLink(links[kind],'Artificial Analysis')}<span>Curated ${esc(C.CURATED_ASOF)}</span></div></aside></div></div>`;
 wireList(root,data,kind);
 root.querySelector('[data-score-help]').onclick=()=>openDialog('Understanding the score',`<p>${esc(kind==='text'?explanations[benchmark]:'Elo measures relative human preference in head-to-head comparisons. Compare scores only within the same arena and configuration.')}</p><p>Bars scale to the leading score in this view; they are not percentages. Model details include configuration notes and limitations.</p>${sourceLink(links[kind],'Read the evaluation methodology')}`);
 root.querySelector('#benchmark')?.addEventListener('change',e=>{benchmark=e.target.value;selected=[];status().textContent='Comparison cleared because the evaluation changed.';renderCategory('text');tray();root.querySelector('#benchmark').focus({preventScroll:true});});
}
function local(){
 const root=document.getElementById('model-local');
 root.innerHTML=`<div class="rank-dashboard local-workspace"><div class="rank-toolbar"><div><h2>AI on your own device</h2><span class="rank-count">Hardware-fit explorer</span></div><span class="rank-count">Curated ${esc(C.CURATED_ASOF)}</span></div><div class="rank-layout"><div class="local-main"><div class="local-filters"><label>Your device<select id="local-device"><option value="pc">PC / laptop</option><option value="phone">Phone / tablet</option></select></label><label>Available RAM<select id="local-ram"><option value="">All memory tiers</option>${[4,6,8,16,24,32,48,64].map(n=>`<option value="${n}">${n} GB</option>`).join('')}</select></label><p id="local-count" role="status"></p></div><div id="local-results"></div></div><aside class="rank-guide"><p class="rank-guide-label">FIND YOUR FIT</p><h3>Small enough to run.<br>Useful enough to keep.</h3><p>Start with your device and memory. These are editorial picks for hardware fit, not a quality ranking.</p><div class="rank-top"><span>Before you download</span><strong>Leave room to think.</strong><p>Your operating system, the AI runtime, and longer conversations all need memory too.</p></div><p>RAM alone doesn’t guarantee compatibility or speed. Read each model’s setup notes.</p><div class="rank-provenance">${sourceLink(links.local,'Explore model cards')}<span>Quantized model estimates</span></div></aside></div></div>`;
 const device=root.querySelector('#local-device'),ram=root.querySelector('#local-ram');
 function draw(){
  const pc=device.value==='pc',data=pc?C.localAI:C.localAiMobile,minimum=pc?[8,16,24,32,48]:[6,8,8,4,4],specs=pc?C.localAiPcSpecs:C.localAiMobileSpecs;
  const filtered=data.filter((r,i)=>!ram.value||minimum[i]<=Number(ram.value));
  root.querySelector('#local-count').textContent=`${filtered.length} of ${data.length} picks`;
  const out=root.querySelector('#local-results');
  out.innerHTML=filtered.length?`<div class="ranking-scroll"><table class="local-table"><caption class="sr-only">Editorial model picks matching your memory filter; hardware estimates, not quality rankings.</caption><thead><tr><th scope="col">Model / provider</th><th scope="col">Device guidance</th><th scope="col">Model footprint</th></tr></thead><tbody>${filtered.map(r=>{const spec=specs.find(s=>s.model===r.model);return `<tr><th scope="row"><button class="rank-model" data-details="${esc(r.model)}"><span class="provider-avatar" aria-hidden="true">${esc(r.org.slice(0,2).toUpperCase())}</span><span><strong>${esc(r.model)}</strong><small>${esc(r.org)}</small></span></button></th><td><span class="memory-pill">${esc(r.stat.replace('Runs on ',''))}</span><small>${esc(spec?.tierLabel||'Hardware estimate')}</small></td><td><strong>${esc(spec?.approxSize||'Not available')}</strong><small>${esc(spec?.params||'')} parameters</small></td></tr>`;}).join('')}</tbody></table></div>`:'<p class="empty-state">No match in this curated dataset. Try another memory tier or device.</p>';
  out.innerHTML+=`<details class="local-specs"><summary>Hardware assumptions & specifications</summary><p>${esc(C.LOCAL_AI_SPECS_METHODOLOGY)}</p>${specs.filter(s=>filtered.some(r=>r.model===s.model)).map(s=>`<div class="benchmark-info"><strong>${esc(s.model)}</strong><p>${esc(s.setup)}</p></div>`).join('')}</details>`;
  wireList(out,filtered,'local');
 }
 device.onchange=draw;ram.onchange=draw;draw();
}
export function initModels(){['text','image','video'].forEach(renderCategory);local();addEventListener('app:view',e=>{const next=e.detail.category;if(e.detail.view==='models'&&next!==category){category=next;selected=[];status().textContent='Comparison cleared because the category changed.';if(['text','image','video'].includes(next)){rows=next==='text'?C.LEADERBOARD_VIEWS.find(v=>v.id===benchmark).data:next==='image'?C.imageAI:C.videoAI;}syncChecks();tray();}});}
