import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { adoptionSummary,adoptionMetric,formatShare } from '../js/metric-meta.js';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const js=readFileSync(new URL('../js/landing.js',import.meta.url),'utf8');
test('landing offers actionable previews and semantic dashboard links',()=>{for(const id of ['lp-brief','lp-models','lp-model-link'])assert.ok(html.includes(`id="${id}"`));assert.match(html,/app.html\?view=today/);assert.match(html,/app.html\?view=models/);assert.match(js,/category='\+category/);assert.match(html,/data-ocean-video/);assert.match(html,/data-wave-toggle/);});
test('landing and dashboard share the briefing renderer',()=>{assert.match(js,/renderBrief/);const main=readFileSync(new URL('../js/main.js',import.meta.url),'utf8');assert.match(main,/renderBrief/);assert.match(js,/CURATED_ASOF/);assert.match(js,/snapshotLabel/);});
test('popularity narrative is derived from the chart rows',()=>{assert.match(adoptionSummary([{name:'Test A',pct:20},{name:'Test B',pct:80}]),/Test B.*80%/);assert.match(adoptionSummary([]),/No referral data/);assert.equal(formatShare(.02),'<0.1%');assert.equal(formatShare(0),'0%');assert.equal(adoptionMetric.sourceName,'Statcounter');assert.match(adoptionMetric.definition,/referrals/);});
test('conflicting popularity narrative and visit total do not ship',()=>{const app=readFileSync(new URL('../app.html',import.meta.url),'utf8');assert.doesNotMatch(app,/53\.9|2\.9B|Fastest mover|Similarweb/);});
